client_config_backend: settings
client_config:
  client_id: 1001561263671-gcn2sogr6a31tl3pegd95ah18356jell.apps.googleusercontent.com
  client_secret: BgUH3Xv_326frwdgMy9iFygm

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json
get_refresh_token: True
oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install